/* DATABASE - CREAZIONE */
DROP DATABASE IF EXISTS merceria;
CREATE DATABASE merceria;
USE merceria;

DROP TABLE IF EXISTS Cliente;
CREATE TABLE Cliente
(
NOME		VARCHAR(15)		NOT NULL,
COGNOME		VARCHAR(15)		NOT NULL,
E_MAIL  	VARCHAR(30)		NOT NULL,
NUM_ORDINI	SMALLINT 		UNSIGNED,
PASS		VARCHAR(20)		NOT NULL,
CAP 		VARCHAR(20)		NOT NULL,
CELLULARE 	VARCHAR(20)		NOT NULL,
CITTA		VARCHAR(20)		NOT NULL,
INDIRIZZO	VARCHAR(20)		NOT NULL,
PROVINCIA	VARCHAR(20)		NOT NULL,		

PRIMARY KEY (E_MAIL)
);

DROP TABLE IF EXISTS Ordine;
CREATE TABLE Ordine
(
DATA_ORDINE			DATE	NOT NULL,
COD_ORDINE			VARCHAR(40) 		NOT NULL,
COSTO_TOTALE   		vArchar(40),
STATO				VARCHAR(20),
PAGAMENTO 			VARCHAR(20),
E_MAIL				VARCHAR(30)		NOT NULL, 	

PRIMARY KEY (COD_ORDINE),
FOREIGN KEY (E_MAIL) REFERENCES Cliente(E_MAIL) ON DELETE CASCADE ON UPDATE CASCADE
);


DROP TABLE IF EXISTS Prodotto;
CREATE TABLE Prodotto
(	
COD_PRODOTTO	VARCHAR(40) 	NOT NULL, 			
TIPO			VARCHAR(20) 	NOT NULL, 			
CATEGORIA		VARCHAR(20) 	NOT NULL, 			
COSTO			DOUBLE 			NOT NULL,					
DIMENSIONI 		VARCHAR(20),	
NOME			VARCHAR(30),
PUBLISHER		VARCHAR(24),    				
DESCRIZIONE		VARCHAR(3000),
IMMAGINI 		VARCHAR(50),
DISPONIBILITA	smallint,
                
PRIMARY KEY	(COD_PRODOTTO)
);


DROP TABLE IF EXISTS Articolato_da;
CREATE TABLE Articolato_da
(
COD_PRODOTTO	VARCHAR(40)	NOT NULL,
QUANTITA 			smallint,
COD_ORDINE		VARCHAR(40)	NOT NULL,

PRIMARY KEY (COD_PRODOTTO,COD_ORDINE),
FOREIGN KEY (COD_PRODOTTO) REFERENCES Prodotto(COD_PRODOTTO) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (COD_ORDINE) REFERENCES Ordine(COD_ORDINE) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Wishlist_Prodotto;
CREATE TABLE Wishlist_Prodotto
(
COD_PRODOTTO	VARCHAR(40)		NOT NULL,
E_MAIL			VARCHAR(30)		NOT NULL, 

PRIMARY KEY (COD_PRODOTTO,E_MAIL),
FOREIGN KEY (COD_PRODOTTO) REFERENCES Prodotto(COD_PRODOTTO) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (E_MAIL) REFERENCES Cliente(E_MAIL) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Recensione;
CREATE TABLE Recensione
(
COD_RECENSIONE	VARCHAR(40)		NOT NULL,
DESCRIZIONE 	VARCHAR(3000) NOT NULL,
COD_PRODOTTO	VARCHAR(40)		NOT NULL,
E_MAIL			VARCHAR(30)		NOT NULL, 

PRIMARY KEY (COD_RECENSIONE,E_MAIL),
FOREIGN KEY (COD_PRODOTTO) REFERENCES Prodotto(COD_PRODOTTO) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (E_MAIL) REFERENCES Cliente(E_MAIL) ON DELETE CASCADE ON UPDATE CASCADE
);
